// Generate web/src/deployment.ts from deploy/testnet.json so the frontend can
// never drift from what is actually deployed.
//
//   node scripts/write-config.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { ROOT, RPC_URL, NETWORK_PASSPHRASE, loadState } from './lib.mjs';

const state = loadState();
if (!state.contractId) {
  console.error('no contractId in deploy/testnet.json — run scripts/deploy.mjs first');
  process.exit(1);
}

const out = join(ROOT, 'web', 'src', 'deployment.ts');
mkdirSync(dirname(out), { recursive: true });

const body = `// GENERATED by scripts/write-config.mjs — do not edit by hand.
//
// The demo keypairs below are throwaway Stellar TESTNET accounts created by
// scripts/deploy.mjs. They hold no real value. They are in the bundle on purpose:
// the page seeds its own demo board (publishes the grant, pre-bonds BOB and CARA)
// without asking the visitor to be the owner, so the board is populated before a
// judge ever arrives. Never put a mainnet secret here.

export const DEPLOYMENT = {
  rpcUrl: ${JSON.stringify(RPC_URL)},
  networkPassphrase: ${JSON.stringify(NETWORK_PASSPHRASE)},
  contractId: ${JSON.stringify(state.contractId)},
  xlmSac: ${JSON.stringify(state.xlmSac)},
  grantIdHex: ${JSON.stringify(state.grantIdHex)},
  explorer: 'https://stellar.expert/explorer/testnet',
  demo: {
    owner: {
      public: ${JSON.stringify(state.deployer.public)},
      secret: ${JSON.stringify(state.deployer.secret)},
    },
    bob: {
      label: 'BOB',
      public: ${JSON.stringify(state.bob.public)},
      secret: ${JSON.stringify(state.bob.secret)},
      credentialSeed: 0x11,
    },
    cara: {
      label: 'CARA',
      public: ${JSON.stringify(state.cara.public)},
      secret: ${JSON.stringify(state.cara.secret)},
      credentialSeed: 0x22,
    },
  },
} as const;
`;

writeFileSync(out, body);
console.log(`wrote ${out}`);
console.log(`  contract  ${state.contractId}`);
console.log(`  grant     ${state.grantIdHex}`);
