// GENERATED by scripts/write-config.mjs — do not edit by hand.
//
// The demo keypairs below are throwaway Stellar TESTNET accounts created by
// scripts/deploy.mjs. They hold no real value. They are in the bundle on purpose:
// the page seeds its own demo board (publishes the grant, pre-bonds BOB and CARA)
// without asking the visitor to be the owner, so the board is populated before a
// judge ever arrives. Never put a mainnet secret here.

export const DEPLOYMENT = {
  rpcUrl: "https://soroban-testnet.stellar.org",
  networkPassphrase: "Test SDF Network ; September 2015",
  contractId: "CCJU4K6VPLUNLRSBEBMF73F7Q6VWIV74WGWDUBJKSYSOTJN3LCDOP4V3",
  xlmSac: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  grantIdHex: "a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1",
  explorer: 'https://stellar.expert/explorer/testnet',
  demo: {
    owner: {
      public: "GCHAXXWL5MDBQ7WSXVWA2WQTIW4FGW35QWMPGZSF655YMMFOSVM5QK3X",
      secret: "SAIJUQ24VLF2XD6CSBXZSBYQJJW7IUXKFHSMFFAILHSXKRJMOK4VFDGG",
    },
    bob: {
      label: 'BOB',
      public: "GCEGQ72V3RLSOQMXBKEX26W5Y3NJRCYDVPDH6PS4P2GIG4WFYN6734DO",
      secret: "SAA7UXFDFOP6NOOIY32WMF6LET4AK3X2ESTOLID52OB5UPP5XYOWFM7M",
      credentialSeed: 0x11,
    },
    cara: {
      label: 'CARA',
      public: "GAS272JXFFQEMLMKGR7IYZOQLM7CIOKS46T6A3OWP2EQDYR534WNDI2G",
      secret: "SAMHV4NQ6IY5WTYL4FGL25KC6XMHVPT7VG64NH6ZN7DEYNG5XKSAIP5W",
      credentialSeed: 0x22,
    },
  },
} as const;
